export const PROBLEMS_LOADED_BEGIN = "PROBLEMS_LOADED_BEGIN";
export const PROBLEMS_LOADED_COMPLETE = "PROBLEMS_LOADED_COMPLETE";
export const PROBLEMS_LOADED_SUCCESS = "PROBLEMS_LOADED_SUCCESS";
export const PROBLEMS_BY_ID_LOADED_SUCCESS = "PROBLEMS_BY_ID_LOADED_SUCCESS";
export const PROBLEMS_BY_SLUG_LOADED_SUCCESS =
  "PROBLEMS_BY_SLUG_LOADED_SUCCESS";

export const ADD_UPDATE_PROBLEM_BEGIN = "ADD_UPDATE_PROBLEM_BEGIN";
export const ADD_UPDATE_PROBLEM_COMPLETE = "ADD_UPDATE_PROBLEM_COMPLETE";
export const UPDATE_PROBLEM_IN_PROBLEM_BY_ID_SUCCESS =
  "UPDATE_PROBLEM_IN_PROBLEM_BY_ID_SUCCESS";

export const ADD_PROBLEM_IN_PROBLEMS_BY_ID_SUCCESS =
  "ADD_PROBLEM_IN_PROBLEMS_BY_ID_SUCCESS";
export const ADD_PROBLEM_IN_PROBLEMS_SUCCESS =
  "ADD_PROBLEM_IN_PROBLEMS_SUCCESS";
export const ADD_PROBLEM_IN_PROBLEMS_BY_SLUG_SUCCESS =
  "ADD_PROBLEM_IN_PROBLEMS_BY_SLUG_SUCCESS";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const ADD_USER = "SET_USER_BY_ID";

export const SIGNUP_BEGIN = "SIGNUP_BEGIN";
export const SIGNUP_COMPLETE = "SIGNUP_COMPLETE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const LOG_OUT_BEGIN = "LOG_OUT_BEGIN";
export const LOG_OUT_COMPLETE = "LOG_OUT_COMPLETE";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";

export const SET_TOKEN_EXPIRY = "VERIFY_TOKEN_EXPIRY";
export const SET_CONSTANTS = "SET_CONSTANTS";

export const UPDATE_PROBLEM_SOURCE_CODE_SUCCESS =
  "UPDATE_PROBLEM_SOURCE_CODE_SUCCESS";

export const UPDATE_PROBLEM_META_DATA_SUCCESS =
  "UPDATE_PROBLEM_META_DATA_SUCCESS";

export const ADD_TEST_CASE_BEGIN = "ADD_TEST_CASE_BEGIN";
export const ADD_TEST_CASE_SUCCESS = "ADD_TEST_CASE_SUCCESS";
export const ADD_TEST_CASE_COMPLETE = "ADD_TEST_CASE_COMPLETE";

export const UPDATE_TEST_CASE_BEGIN = "UPDATE_TEST_CASE_BEGIN";
export const UPDATE_TEST_CASE_SUCCESS = "UPDATE_TEST_CASE_SUCCESS";
export const UPDATE_TEST_CASE_COMPLETE = "UPDATE_TEST_CASE_COMPLETE";

export const DELETE_TEST_CASE_BEGIN = "DELETE_TEST_CASE_BEGIN";
export const DELETE_TEST_CASE_SUCCESS = "DELETE_TEST_CASE_SUCCESS";
export const DELETE_TEST_CASE_COMPLETE = "DELETE_TEST_CASE_COMPLETE";

export const LOAD_TRY_CODE_BEGIN = "LOAD_TRY_CODE_BEGIN";
export const LOAD_TRY_CODE_COMPLETE = "LOAD_TRY_CODE_COMPLETE";

export const LOAD_CREATE_UPDATE_PAGE_BEGIN = "LOAD_CREATE_UPDATE_PAGE_BEGIN";
export const LOAD_CREATE_UPDATE_PAGE_COMPLETE =
  "LOAD_CREATE_UPDATE_PAGE_COMPLETE";
